### PR TITLE
Discretize ORB patch orientation

### PR DESCRIPTION
**Pull request by martinpucala**
In the ORB paper the patch orientation is discretized into 30 steps 12-degree steps. Subjectively it was giving me better results when processing and especially matching live camera feed.

Next step could be adding the missing 29 sets of 256 test pairs coordinates and save sin/cos calculation for each keypoint.

### CODE REVIEW

**Review by alemart — CHANGES_REQUESTED** [review]
Thank you for contributing to speedy-vision.js.

Please amend your commit message and include a Developer Certificate of Origin sign-off, as demonstrated in [CONTRIBUTING.md](https://github.com/alemart/speedy-vision-js/blob/master/CONTRIBUTING.md).

**Comment by martinpucala** [comment]
Thanks, done.

**Review by alemart — CHANGES_REQUESTED** [review]
Thank you!

Regarding your patch:
1. What about using `round()` instead of `floor()` when setting degreesOrientation?
```
float degreesOrientation = round(degrees(keypoint.orientation));
```
2. Since degreesOrientation is an integer value, wouldn't it be better to omit the call to `floor()` when setting variable orientation?
```
float orientation = radians(degreesOrientation - mod(degreesOrientation, 12.0f));
```
3. Finally, line `@include "math.glsl"` is not needed and can be removed.

**Review by alemart — APPROVED** [review]
Thank you.

**Pull request merged**
